# Generated by Django 5.0.1 on 2024-01-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
