# Generated by Django 5.0.1 on 2024-01-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='details',
            new_name='description',
        ),
    ]
