# Generated by Django 5.0.1 on 2024-01-13 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0005_alter_task_options_task_complete_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number')),
                ('about_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='About user')),
                ('publisher', models.BooleanField(default=True, verbose_name='Publisher')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
