# Generated by Django 5.0.1 on 2024-01-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
