# Generated by Django 5.0.1 on 2024-01-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0007_remove_profile_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
